---
version: "2.1"
services:
  plex:
    image: ghcr.io/linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM= #optional
    volumes:
      - /vms/docker-configs/plex:/config
      - /storage/plex/tv:/tv
      - /storage/plex/movies:/movies
    ports:
      - 32400:32400
    restart: unless-stopped
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /vms/docker-configs/plsonarrex:/config
      - /storage/plex/tv:/tv
      - /storage/sabnzbd/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /vms/docker-configs/radarr:/config
      - /storage/plex/movies:/movies
      - /storage/sabnzbd/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  lidarr:
    image: ghcr.io/linuxserver/lidarr
    container_name: lidarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - UMASK_SET=022 #optional
    volumes:
      - /vms/docker-configs/lidarr:/config
      - /storage/plex/music:/music
      - /storage/sabnzbd/downloads:/downloads
    ports:
      - 8686:8686
    restart: unless-stopped
  sabnzbd:
    image: ghcr.io/linuxserver/sabnzbd
    container_name: sabnzbd
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - /vms/docker-configs/sabnzbd:/config
      - /storage/sabnzbd/downloads:/downloads
      - /storage/sabnzbd/incomplete:/incomplete-downloads #optional
    ports:
      - 8080:8080
      - 9090:9090
    restart: unless-stopped
  lazylibrarian:
    image: ghcr.io/linuxserver/lazylibrarian
    container_name: lazylibrarian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - DOCKER_MODS=linuxserver/calibre-web:calibre|linuxserver/mods:lazylibrarian-ffmpeg #optional
    volumes:
      - /vms/docker-configs/lazylibrarian:/config
      - /storage/sabnzbd/downloads:/downloads
      - /storage/books:/books
    ports:
      - 5299:5299
    restart: unless-stopped